apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: register-flyte-pipeline-
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    steps:
    - - name: clone-repo
        template: git-clone
    - - name: parse-github-repo
        template: parse-github-repo
    - - name: register-and-run
        arguments:
          artifacts:
            - name: home-dir
              from: "{{steps.clone-repo.outputs.artifacts.home}}"
          parameters:
            - name: version
              value: "{{steps.clone-repo.outputs.result}}"
            - name: repo-name-with-owner
              value: "{{steps.parse-github-repo.outputs.result}}"
        template: register-and-run
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: $GITHUB_REPO
          revision: HEAD
          usernameSecret:
            name: github-creds
            key: username
          passwordSecret:
            name: github-creds
            key: password
    script:
      image: bitnami/git:2.34.1
      command: [bash]
      source: |
        git show -s --format=%h-$${q}RANDOM
      workingDir: /src
    outputs:
      artifacts:
        - name: home
          path: /src
  - name: parse-github-repo
    script:
      image: bitnami/git:2.34.1
      command: [bash]
      source: |
        GITHUB_REPO=$GITHUB_REPO
        owner_url=$(dirname $${q}GITHUB_REPO)
        OWNER_NAME=$(basename $${q}owner_url)
        REPO_NAME_BASE=$(basename $${q}GITHUB_REPO)
        REPO_NAME=${REPO_NAME_BASE%.*}
        echo $${q}OWNER_NAME/$${q}REPO_NAME
      workingDir: /tmp
  - name: register-and-run
    inputs:
      artifacts:  
      - name: home-dir
        path: /src
      parameters:
      - name: version
      - name: repo-name-with-owner
    script:
      image: k3d-registry.localhost:5000/workflow:latest
      command: [bash]
      source: |
        pyflyte --pkgs flytesnacks.workflows.$WORKFLOW package --fast --source . --image k3d-registry.localhost:5000/workflow:latest -f

        cat > config.yaml <<'_EOF'
        admin:
          # For GRPC endpoints you might want to use dns:///flyte.myexample.com
          endpoint: dns:///flyteadmin.flyte.svc.cluster.local:81
          authType: Pkce
          insecure: true
        logger:
          show-source: true
          level: 0
        storage:
          connection:
            access-key: minio
            auth-type: accesskey
            disable-ssl: true
            endpoint: http://minio.flyte.svc.cluster.local:9000
            region: us-east-1
            secret-key: miniostorage
          type: minio
          container: "my-s3-bucket"
          enable-multicontainer: true
        _EOF

        cat > exec_spec_workflow_part1.yaml <<'_EOF'
        iamRoleARN: ""
        targetDomain: "development"
        targetProject: "flytesnacks"
        version: {{inputs.parameters.version}}
        workflow: flytesnacks.workflows.$WORKFLOW.pipeline
        _EOF

        cat > exec_spec_workflow_part2.yaml <<'_EOF'
        iamRoleARN: ""
        inputs:
            min_auc: 0.95
            n_estimators: 100
            test_size: 0.3
        targetDomain: "development"
        targetProject: "flytesnacks"
        version: {{inputs.parameters.version}}
        workflow: flytesnacks.workflows.$WORKFLOW.pipeline
        _EOF
        
        cat > exec_spec_workflow_part3.yaml <<'_EOF'
        iamRoleARN: ""
        inputs:
            min_auc: 0.95
            n_estimators: 100
            repository: {{inputs.parameters.repo-name-with-owner}}
            test_size: 0.3
        kubeServiceAcct: "model-deployer-service-account"
        targetDomain: "development"
        targetProject: "flytesnacks"
        version: {{inputs.parameters.version}}
        workflow: flytesnacks.workflows.$WORKFLOW.pipeline
        _EOF

        flytectl --config config.yaml register files --project flytesnacks --domain development --archive flyte-package.tgz --version {{inputs.parameters.version}} --k8sServiceAccount model-deployer-service-account
        flytectl --config config.yaml create execution --project flytesnacks --domain development --execFile exec_spec_$WORKFLOW.yaml
      workingDir: /src
